# Enable Gradle configuration cache if you'd like:
# Of course, only do it if https://github.com/gradle/gradle/issues/18520 is fixed
org.gradle.configuration-cache=false

# Project
group = io.siuolplex

# Minecraft Details
minecraft_version = 26.1.2
minecraft_target_version = 26.1.2
java_version = 25

# Mod Details
mod_id = wood_you_dye
version = 3.0.0
mod_name = Wood You Dye
mod_license = MIT
mod_author = Siuolplex

# Neoform Details, used for common
# https://projects.neoforged.net/neoforged/neoform
neoform_version = 26.1.2-1

# Misc Mixin details that I meticulously worry about but shouldn't concern you I hope (Come on please dont be concerned)
mixin_version = 0.8.7
# Fabric Mixin is used in more than just Fabric! Check https://github.com/FabricMC/fabric-loader/blob/master/gradle.properties#L12 and https://github.com/neoforged/NeoForge/blob/master/gradle.properties#L37 for more info
fabric_mixin_version = 0.17.2
mixin_extras_version = 0.5.4

# Fabric Details
# https://fabricmc.net/develop/
fabric_loader_version = 0.19.2
fabric_api_version = 0.146.1

# Neoforge Details
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version = 26.1.2.22-beta

# Gremlib
gremlib_version = 0.1.0
