name: Manual Build
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Is this build a release?'
        required: false
        default: false
        type: boolean
      publish-cf:
        description: 'Do we publish build on Curseforge?'
        required: false
        default: false
        type: boolean
      publish-mr:
        description: 'Do we publish build on Modrinth?'
        required: false
        default: false
        type: boolean
      publish-gh:
        description: 'Do we publish build on Github?'
        required: false
        default: false
        type: boolean

env:
  RELEASE_MODE: ${{ inputs.release }}
  PUBLISH_MR: ${{inputs.publish-mr}}
  PUBLISH_CF: ${{inputs.publish-cf}}
  PUBLISH_GH: ${{inputs.publish-gh}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build
      - name: Publish Mod
        run: ./gradlew publish
        env:
          DEVOS_USERNAME: ${{ secrets.DEVOS_USER }}
          DEVOS_PASSWORD: ${{ secrets.DEVOS_PASSWORD }}

      - name: Upload Mod
        if: ${{ inputs.release }}
        run: ./gradlew uploadMod
        env:
          MODRINTH_PAT: ${{secrets.MODRINTH_PAT}}
          CURSEFORGE_TOKEN: ${{secrets.CURSEFORGE_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            fabric/build/libs/
            neoforge/build/libs/
            common/build/libs/
