name: Build Mod
on: [ pull_request, push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        # Ok so release mode is false for now but I do want to get an actual release system ready.
        run: |
          RELEASE_MODE=${{false}} \
          ./gradlew build

      - name: Publish Mod
        run: ./gradlew publish
        env:
          DEVOS_USERNAME: ${{ secrets.DEVOS_USER }}
          DEVOS_PASSWORD: ${{ secrets.DEVOS_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: |
            fabric/build/libs/
            neoforge/build/libs/
            common/build/libs/
